"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-22 21:18:21.897597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('hotspot_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('registration_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('device_mac', sa.String(length=17), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('current_ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor_guess', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('mikrotik_bound', sa.Boolean(), nullable=False),
    sa.Column('mikrotik_bypassed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_group_id'), 'devices', ['group_id'], unique=False)
    op.create_index(op.f('ix_devices_mac'), 'devices', ['mac'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('device_mqtt_state',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.String(length=100), nullable=True),
    sa.Column('discovery_published_at', sa.DateTime(), nullable=True),
    sa.Column('last_state_published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('device_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('service_guess', sa.String(length=100), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_scan_results_device_id'), 'device_scan_results', ['device_id'], unique=False)
    # ### end Alembic commands ###

    # Seed data: exactly two groups, matching today's real MikroTik policy
    # (a subnet-wide bypass minus a handful of named exceptions). New
    # devices discovered by the sync loop land in whichever group has
    # is_default=True — see app/sync.py:_default_group_id.
    groups_table = sa.table(
        "groups",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("hotspot_required", sa.Boolean),
        sa.column("description", sa.String),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(
        groups_table,
        [
            {
                "id": 1,
                "name": "Liberado",
                "hotspot_required": False,
                "description": "Free access, does not go through the hotspot (default for new devices)",
                "is_default": True,
            },
            {
                "id": 2,
                "name": "Hotspot",
                "hotspot_required": True,
                "description": "Requires MikroTik hotspot login, subject to daily quota",
                "is_default": False,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_scan_results_device_id'), table_name='device_scan_results')
    op.drop_table('device_scan_results')
    op.drop_table('device_mqtt_state')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac'), table_name='devices')
    op.drop_index(op.f('ix_devices_group_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('users')
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    op.drop_table('groups')
    # ### end Alembic commands ###
