"""quota engine

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-22 23:28:03.776847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('limit_s', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quota_log_user_id'), 'quota_log', ['user_id'], unique=False)
    op.add_column('groups', sa.Column('daily_limit_weekday_s', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('daily_limit_weekend_s', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('night_block_start', sa.String(length=5), nullable=True))
    op.add_column('groups', sa.Column('night_block_end', sa.String(length=5), nullable=True))
    op.add_column('groups', sa.Column('night_block_address_list', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('mikrotik_username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('daily_limit_weekday_s', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('daily_limit_weekend_s', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['mikrotik_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'daily_limit_weekend_s')
    op.drop_column('users', 'daily_limit_weekday_s')
    op.drop_column('users', 'mikrotik_username')
    op.drop_column('groups', 'night_block_address_list')
    op.drop_column('groups', 'night_block_end')
    op.drop_column('groups', 'night_block_start')
    op.drop_column('groups', 'daily_limit_weekend_s')
    op.drop_column('groups', 'daily_limit_weekday_s')
    op.drop_index(op.f('ix_quota_log_user_id'), table_name='quota_log')
    op.drop_table('quota_log')
    # ### end Alembic commands ###
