"""quota engine v2 - self accounting

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-22 23:41:56.139450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seconds_used_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_index(op.f('mikrotik_username'), table_name='users')
    op.drop_column('users', 'mikrotik_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mikrotik_username', mysql.VARCHAR(length=64), nullable=True))
    op.create_index(op.f('mikrotik_username'), 'users', ['mikrotik_username'], unique=True)
    op.drop_column('users', 'blocked')
    op.drop_column('users', 'seconds_used_today')
    # ### end Alembic commands ###
